"""scan_upload error column

Revision ID: 7650f33b3bab
Revises: e73e3475a216
Create Date: 2026-07-27 14:44:54.934695
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7650f33b3bab'
down_revision: str | None = 'e73e3475a216'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_uploads', sa.Column('error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_uploads', 'error')
    # ### end Alembic commands ###
